spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense
    username: postgres
    password: makangratis
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
